package fr.iamacat.optimizationsandtweaks.asm;

import java.util.List;
import java.util.function.Predicate;

import com.falsepattern.lib.mixin.IMixin;
import com.falsepattern.lib.mixin.ITargetedMod;

import fr.iamacat.optimizationsandtweaks.config.OptimizationsandTweaksConfig;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum Mixin implements IMixin {

    common_accessor_PathNavigateAccessor(Side.COMMON, m -> OptimizationsandTweaksConfig.enablePathFindingOptimizations,
        "accessor.PathNavigateAccessor"),

    common_core_MixinWorld(Side.COMMON, always(), "core.MixinWorld"),
    common_core_MixinEventBus(Side.COMMON, always(), "core.MixinEventBus"),
    common_core_MixinExplosion(Side.COMMON, always(), "core.MixinExplosion"),
    common_core_MixinEnchantmentHelper(Side.COMMON, always(), "core.MixinEnchantmentHelper"),
    common_packagedauto_MixinNeiHandlerPackagedAuto(Side.COMMON, require(TargetedMod.PACKAGEDAUTO),
        "packagedauto.MixinNeiHandlerPackagedAuto"),
    common_lotrimprovements_MixinMain(Side.COMMON, require(TargetedMod.LORDOFTHERINGSFORK),
        "lotrimprovements.MixinMain"),
    common_disastercraft_MixinBiomeListDisaster(Side.COMMON, require(TargetedMod.DISASTERCRAFT),
        "disastercraft.MixinBiomeListDisaster"),

    common_disastercraft_MixinMainDisastercraft(Side.COMMON, require(TargetedMod.DISASTERCRAFT),
        "disastercraft.MixinMainDisastercraft"),
    common_minegicka_MixinModBaseMinegicka(Side.COMMON, require(TargetedMod.MINEGICKA),
        "minegicka.MixinModBaseMinegicka"),
    common_animalsplus_MixinEntitySwimming(Side.COMMON, require(TargetedMod.ANIMALSPLUS),
        "animalsplus.MixinEntitySwimming"),
    common_lotr_MixinLOTRMod(Side.COMMON,
        require(TargetedMod.LORDOFTHERINGS).and(avoid(TargetedMod.LORDOFTHERINGSFORK)), "lotr.MixinLOTRMod"),
    common_lotr_MixinLOTRBiome(Side.COMMON,
        require(TargetedMod.LORDOFTHERINGS).and(avoid(TargetedMod.LORDOFTHERINGSFORK)), "lotr.MixinLOTRBiome"),
    common_lotr_MixinLOTRWorldProvider(Side.COMMON,
        avoid(TargetedMod.LORDOFTHERINGSFORK).and(require(TargetedMod.ENDLESSIDS)), "lotr.MixinLOTRWorldProvider"),

    common_mowziesmobs_MixinStructureGeneratorBaseMM(Side.COMMON, require(TargetedMod.MOWZIESMOBS),
        "mowziesmobs.MixinStructureGeneratorBaseMM"),

    common_minestones_MixinItemMinestone(Side.COMMON, require(TargetedMod.MINESTONES), "minestones.MixinItemMinestone"),

    common_minestones_MixinMSConfig(Side.COMMON, require(TargetedMod.MINESTONES), "minestones.MixinMSConfig"),
    common_minestones_MixinMSEvents(Side.COMMON, require(TargetedMod.MINESTONES), "minestones.MixinMSEvents"),
    common_core_MixinBlockFluidClassic(Side.COMMON, always(), "core.MixinBlockFluidClassic"),
    common_core_MixinEntityRegistry(Side.COMMON, always(), "core.MixinEntityRegistry"),
    common_core_MixinEnchantment(Side.COMMON, always(), "core.MixinEnchantment"),
    common_core_MixinWorldType(Side.COMMON, always(), "core.MixinWorldType"),
    common_core_MixinFMLClientHandler(Side.COMMON, always(), "core.MixinFMLClientHandler"),
    common_core_MixinFMLServerHandler(Side.COMMON, always(), "core.MixinFMLServerHandler"),
    common_core_MixinStartupQuery(Side.COMMON,
        m -> OptimizationsandTweaksConfig.enableFMLAutoConfirmAfterFirstConfirmation, "core.MixinStartupQuery"),
    /*
     * todo need to fix was loaded to early crash
     * common_core_MixinLoader(Side.COMMON, m ->
     * OptimizationsandTweaksConfig.enableMixinLoader, "core.MixinLoader"),
     */
    common_core_MixinMinecraft(Side.COMMON, avoid(TargetedMod.FALSETWEAKS), "core.MixinMinecraft"),
    server_core_MixinMinecraftServerGui(Side.SERVER, always(), "core.MixinMinecraftServerGui"),
    common_core_MixinSaveFormatOld(Side.COMMON, always(), "core.MixinSaveFormatOld"),
    common_core_MixinThreadedFileIOBase(Side.COMMON, always(), "core.MixinThreadedFileIOBase"),

    common_core_MixinVec3(Side.COMMON, always(), "core.MixinVec3"),

    common_core_MixinEntityAINearestAttackableTarget(Side.COMMON, always(),
        "core.MixinEntityAINearestAttackableTarget"),
    common_core_MixinEntityList(Side.COMMON, always(), "core.MixinEntityList"),
    common_core_MixinNBTTagCompound(Side.COMMON, avoid(TargetedMod.DRAGONAPI), "core.MixinNBTTagCompound"),
    common_core_MixinNBTBase(Side.COMMON, avoid(TargetedMod.DRAGONAPI), "core.MixinNBTBase"),
    common_core_MixinMapGenStructure(Side.COMMON, avoid(TargetedMod.DRAGONAPI), "core.MixinMapGenStructure"),

    common_core_MixinEntityArrowAttack(Side.COMMON, always(), "core.MixinEntityArrowAttack"),
    common_core_MixinAxisAlignedBB(Side.COMMON, always(), "core.MixinAxisAlignedBB"),
    common_core_MixinEntityAITempt(Side.COMMON, always(), "core.MixinEntityAITempt"),

    common_easybreeding_MixinEntityAIEatDroppedFood(Side.COMMON, require(TargetedMod.EASYBREEDING),
        "easybreeding.MixinEntityAIEatDroppedFood"),
    common_core_MixinEntityAIPlay(Side.COMMON, always(), "core.MixinEntityAIPlay"),
    common_core_MixinServersideAttributeMap(Side.COMMON, always(), "core.MixinServersideAttributeMap"),
    common_core_MixinLowerStringMap(Side.COMMON, always(), "core.MixinLowerStringMap"),
    common_core_MixinEntityLivingBase(Side.COMMON, always(), "core.MixinEntityLivingBase"),
    common_core_MixinDataWatcher(Side.COMMON, always(), "core.MixinDataWatcher"),
    common_blocklings_MixinEntityBlockling(Side.COMMON, require(TargetedMod.BLOCKLINGS),
        "blocklings.MixinEntityBlockling"),
    common_flaxbeardssteampower_MixinSteamcraftEventHandler(Side.COMMON, require(TargetedMod.FLAXBEARDSTEAMPOWER),
        "flaxbeardssteampower.MixinSteamcraftEventHandler"),
    common_catwalks2_MixinCommonProxy(Side.COMMON,
        require(TargetedMod.CATWALK2UNOFFICIAL).and(avoid(TargetedMod.CATWALK2OFFICIAL)), "catwalks2.MixinCommonProxy"),
    common_unuquadium_Mixinmcreator_ununquadiumLand(Side.COMMON, require(TargetedMod.UNUNQUADIUM),
        "unuquadium.Mixinmcreator_ununquadiumLand"),
    common_buildcraft_addon_oiltweaks_MixinOilTweakEventHandler(Side.COMMON, require(TargetedMod.BUILDCRAFTOILTWEAKS),
        "buildcraft.addon.oiltweaks.MixinOilTweakEventHandler"),
    common_buildcraft_MixinBlockBuildCraftFluid(Side.COMMON, require(TargetedMod.BUILDCRAFT),
        "buildcraft.MixinBlockBuildCraftFluid"),
    common_sgstreasure_MixinObsidianChestGenerator(Side.COMMON, require(TargetedMod.SGSTREASURE),
        "sgstreasure.MixinObsidianChestGenerator"),
    common_sgstreasure_MixinPlansProcessor(Side.COMMON, require(TargetedMod.SGSTREASURE),
        "sgstreasure.MixinPlansProcessor"),
    common_sgstreasure_MixinWorldUtilSGSTREASURE(Side.COMMON, require(TargetedMod.SGSTREASURE),
        "sgstreasure.MixinWorldUtilSGSTREASURE"),
    common_core_MixinSaveHandler(Side.COMMON, always(), "core.MixinSaveHandler"),
    common_core_MixinMathHelper(Side.COMMON, always(), "core.MixinMathHelper"),
    common_core_MixinNetworkManager(Side.COMMON, always(), "core.MixinNetworkManager"),
    common_core_MixinEntity(Side.COMMON, always(), "core.MixinEntity"),

    common_core_MixinBlock(Side.COMMON, always(), "core.MixinBlock"),
    common_core_MixinBlockLeaves(Side.COMMON, always(), "core.MixinBlockLeaves"),

    common_core_MixinBiomeCache(Side.COMMON, always(), "core.MixinBiomeCache"),

    client_core_MixinRenderBlocks(Side.CLIENT, always(), "core.MixinRenderBlocks"),

    common_core_MixinForgeHooksClient(Side.COMMON, always(), "core.MixinForgeHooksClient"),
    common_core_MixinStringTranslate(Side.COMMON, always(), "core.MixinStringTranslate"),
    common_core_MixinBlockDynamicLiquid(Side.COMMON, always(), "core.MixinBlockDynamicLiquid"),
    common_core_MixinModifiableAttributeInstance(Side.COMMON, always(), "core.MixinModifiableAttributeInstance"),

    common_core_MixinEntityTracker(Side.COMMON, always(), "core.MixinEntityTracker"),
    common_core_MixinWorldServer(Side.COMMON, avoid(TargetedMod.LAGGOOGLES), "core.MixinWorldServer"),
    common_core_MixinStatsComponent(Side.SERVER, always(), "core.MixinStatsComponent"),

    common_netherlicious_MixinVentGeneratorSingle(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinVentGeneratorSingle"),

    common_netherlicious_MixinWorldGeneratorAdv(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinWorldGeneratorAdv"),
    common_netherlicious_MixinCrystalFormationHangingBig(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinCrystalFormationHangingBig"),
    common_netherlicious_MixinCrystalFormationBig(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinCrystalFormationBig"),
    common_netherlicious_MixinNetherliciousEventHandler(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinNetherliciousEventHandler"),
    common_netherlicious_MixinBiomeBlobGen(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinBiomeBlobGen"),
    common_netherlicious_MixinRuptureSpike(Side.COMMON, require(TargetedMod.NETHERLICIOUS),
        "netherlicious.MixinRuptureSpike"),
    common_KoRIN_MixinKoRINEventHandler(Side.COMMON, require(TargetedMod.KORINBLUEBEDROCK),
        "KoRIN.MixinKoRINEventHandler"),
    common_coroutil_MixinPFQueue(Side.COMMON,
        require(TargetedMod.COROUTIL).and(m -> OptimizationsandTweaksConfig.enablePathFindingOptimizations),
        "coroutil.MixinPFQueue"),
    common_coroutil_MixinPFQueueTryPath(Side.COMMON,
        require(TargetedMod.COROUTIL).and(m -> OptimizationsandTweaksConfig.enablePathFindingOptimizations),
        "coroutil.MixinPFQueueTryPath"),
    common_zombieawareness_MixinZAUtil(Side.COMMON, require(TargetedMod.COROUTIL), "zombieawareness.MixinZAUtil"),
    common_minenautica_MixinBiomeRegistry(Side.COMMON, require(TargetedMod.MINENAUTICA),
        "minenautica.MixinBiomeRegistry"),
    common_minenautica_MixinMinenautica(Side.COMMON, require(TargetedMod.MINENAUTICA), "minenautica.MixinMinenautica"),
    common_lotofmobs_MixinLotsOMobs(Side.COMMON, require(TargetedMod.LOTOFMOBS), "lotofmobs.MixinLotsOMobs"),
    common_lotofmobs_MixinLotsOMobsBiomes(Side.COMMON, require(TargetedMod.LOTOFMOBS),
        "lotofmobs.MixinLotsOMobsBiomes"),
    common_lotofthings_MixinGenRainbowFlowers(Side.COMMON, require(TargetedMod.LOTSOFTHINGS),
        "lotofthings.MixinGenRainbowFlowers"),
    common_lotofthings_MixinLOTGeneration(Side.COMMON, require(TargetedMod.LOTSOFTHINGS),
        "lotofthings.MixinLOTGeneration"),
    common_themistsofriov_MixinWorldGenBalance(Side.COMMON, require(TargetedMod.THEMISTOFRIOV),
        "themistsofriov.MixinWorldGenBalance"),
    common_thetitan_MixinWorldHandlerTitan(Side.COMMON, require(TargetedMod.THETITANS),
        "thetitan.MixinWorldHandlerTitan"),
    common_thetitan_MixinFixMinionIaTitan(Side.COMMON, require(TargetedMod.THETITANS),
        "thetitan.MixinFixMinionIaTitan"),
    common_structpro_MixinUWorld(Side.COMMON, require(TargetedMod.STRUCTPRO), "structpro.MixinUWorld"),
    common_thecampingmod_MixinWorldGeneratorTheCamping(Side.COMMON, require(TargetedMod.THECAMPINGMOD),
        "thecampingmod.MixinWorldGeneratorTheCamping"),
    common_minenautica_MixinAluminumOxideWorldGen(Side.COMMON, require(TargetedMod.MINENAUTICA),
        "minenautica.MixinAluminumOxideWorldGen"),
    common_minenautica_MixinGenerateCoral(Side.COMMON, require(TargetedMod.MINENAUTICA),
        "minenautica.MixinGenerateCoral"),
    common_minenautica_MixinBloodgrass(Side.COMMON, require(TargetedMod.MINENAUTICA), "minenautica.MixinBloodgrass"),
    common_minenautica_MixinCanBlockStay(Side.COMMON, require(TargetedMod.MINENAUTICA),
        "minenautica.MixinCanBlockStay"),
    common_minenautica_MixinBiomeGenGrassyPlateaus(Side.COMMON, require(TargetedMod.MINENAUTICA),
        "minenautica.MixinBiomeGenGrassyPlateaus"),
    common_minenautica_MixinBiomeGenKelpForest(Side.COMMON, require(TargetedMod.MINENAUTICA),
        "minenautica.MixinBiomeGenKelpForest"),
    common_fantasticfish_MixinFantasticEvents(Side.COMMON, require(TargetedMod.FANTASTICFISH),
        "fantasticfish.MixinFantasticEvents"),
    common_fantasticfish_MixinFantasticMod(Side.COMMON, require(TargetedMod.FANTASTICFISH),
        "fantasticfish.MixinFantasticMod"),
    common_akatsuki_MixinEntitySasori(Side.COMMON, require(TargetedMod.AKATSUKI), "akatsuki.MixinEntitySasori"),
    common_akatsuki_MixinEntitySasori2(Side.COMMON, require(TargetedMod.AKATSUKI), "akatsuki.MixinEntitySasori2"),
    common_akatsuki_MixinPuppetKadz(Side.COMMON, require(TargetedMod.AKATSUKI), "akatsuki.MixinPuppetKadz"),
    common_akatsuki_MixinAnimTickHandler(Side.COMMON, require(TargetedMod.AKATSUKI), "akatsuki.MixinAnimTickHandler"),
    common_akatsuki_MixinAnimationHandler(Side.COMMON, require(TargetedMod.AKATSUKI), "akatsuki.MixinAnimationHandler"),
    common_aether_MixinPlayerAether(Side.COMMON, require(TargetedMod.AETHER), "aether.MixinPlayerAether"),
    common_aether_MixinPlayerAetherEvents(Side.COMMON, require(TargetedMod.AETHER), "aether.MixinPlayerAetherEvents"),
    common_cofhcore_MixinHooksCore(Side.COMMON, require(TargetedMod.COFHCORE), "cofhcore.MixinHooksCore"),
    common_thaumicrevelation_MixinWardenicChargeEvents(Side.COMMON, require(TargetedMod.THAUMICREVELEATION),
        "thaumicrevelation.MixinWardenicChargeEvents"),
    common_aether_MixinAetherTileEntities(Side.COMMON, require(TargetedMod.AETHER), "aether.MixinAetherTileEntities"),
    common_etfuturumrequiem_MixinUtils(Side.COMMON, require(TargetedMod.ETFUTURMREQUIEM),
        "etfuturumrequiem.MixinUtils"),
    common_etfuturumrequiem_MixinDeepslateOreRegistry(Side.COMMON, require(TargetedMod.ETFUTURMREQUIEM),
        "etfuturumrequiem.MixinDeepslateOreRegistry"),
    common_notenoughpets_MixinEventHandlerNEP(Side.COMMON, require(TargetedMod.NOTENOUGHPETS),
        "notenoughpets.MixinEventHandlerNEP"),
    common_pneumaticraft_MixinHackTickHandler(Side.COMMON, require(TargetedMod.PNEUMATICRAFT),
        "pneumaticraft.MixinHackTickHandler"),
    common_ic2_MixinPriorityExecutor(Side.COMMON, require(TargetedMod.INDUSTRIALCRAFT), "ic2.MixinPriorityExecutor"),
    common_growthcraft_MixinAppleFuelHandler(Side.COMMON, require(TargetedMod.GROWTHCRAFT),
        "growthcraft.MixinAppleFuelHandler"),
    common_adventurersamulet_MixinEntityEagle(Side.COMMON, require(TargetedMod.ADVENTURERS_AMULETS),
        "adventurersamulet.MixinEntityEagle"),

    common_ppap_MixinPPAPEventHandler(Side.COMMON, require(TargetedMod.PPAPMOD), "ppap.MixinPPAPEventHandler"),
    common_core_MixinEntityLiving(Side.COMMON, always(), "core.MixinEntityLiving"),
    common_core_MixinEntityAgeable(Side.COMMON, always(), "core.MixinEntityAgeable"),
    common_nei_MixinNEIServerUtils(Side.COMMON, require(TargetedMod.NEI), "nei.MixinNEIServerUtils"),
    common_nei_MixinConfig(Side.COMMON, require(TargetedMod.NEI), "ic2.MixinConfig"),
    common_core_MixinBlockLiquid(Side.COMMON, always(), "core.MixinBlockLiquid"),
    common_core_entity_MixinEntityZombie(Side.COMMON, always(), "core.entity.MixinEntityZombie"),

    common_core_entity_MixinEntityItem(Side.COMMON, always(), "core.entity.MixinEntityItem"),
    common_ic2_MixinTickHandler(Side.COMMON, require(TargetedMod.INDUSTRIALCRAFT), "ic2.MixinTickHandler"),

    common_core_entity_MixinEntityAnimal(Side.COMMON, always(), "core.entity.MixinEntityAnimal"),

    common_core_biomes_MixinBiomeGenBase(Side.COMMON, avoid(TargetedMod.DRAGONAPI).and(avoid(TargetedMod.ALFHEIM)),
        "core.biomes.MixinBiomeGenBase"),
    common_core_MixinCompressedStreamTools(Side.COMMON, always(), "core.MixinCompressedStreamTools"),
    common_core_MixinLaunchClassLoader(Side.COMMON, always(), "core.MixinLaunchClassLoader"),
    common_core_entity_MixinEntitySquid(Side.COMMON, always(), "core.entity.MixinEntitySquid"),
    common_core_MixinWorldChunkManager(Side.COMMON, always(), "core.MixinWorldChunkManager"),
    common_core_MixinExtendedBlockStorage(Side.COMMON, always(), "core.MixinExtendedBlockStorage"),
    common_core_MixinEntityMoveHelper(Side.COMMON, always(), "core.MixinEntityMoveHelper"),
    common_core_MixinWorldGenMinable(Side.COMMON, always(), "core.MixinWorldGenMinable"),
    common_core_MixinLanguageRegistry(Side.COMMON, always(), "core.MixinLanguageRegistry"),
    common_core_MixinEntityAIFollowParent(Side.COMMON, always(), "core.MixinEntityAIFollowParent"),
    common_core_MixinEntityMob(Side.COMMON, always(), "core.MixinEntityMob"),
    common_jewelrycraft2_MixinEntityEventHandler(Side.COMMON, require(TargetedMod.JEWELRYCRAFT2),
        "jewelrycraft2.MixinEntityEventHandler"),
    common_portalgun_MixinSettings(Side.COMMON, require(TargetedMod.PORTALGUN), "portalgun.MixinSettings"),
    common_core_MixinEntityLookHelper(Side.COMMON, always(), "core.MixinEntityLookHelper"),
    common_core_MixinBlockFalling(Side.COMMON, always(), "core.MixinBlockFalling"),

    common_koto_MixinPatchWorldGenCloudNine(Side.COMMON, require(TargetedMod.KINGDOMSOFTHEOVERWORLD),
        "koto.MixinPatchWorldGenCloudNine"),
    common_koto_MixinEntityDarkMiresi(Side.COMMON, require(TargetedMod.KINGDOMSOFTHEOVERWORLD),
        "koto.MixinEntityDarkMiresi"),
    common_tconstruct_MixinTinkerGears(Side.COMMON, require(TargetedMod.TCONSTRUCT), "tconstruct.MixinTinkerGears"),
    common_core_MixinTileEntityRendererDispatcher(Side.COMMON, always(), "core.MixinTileEntityRendererDispatcher"),
    common_weathercarpet_MixinCloudChecking(Side.COMMON, require(TargetedMod.WEATHERCARPET),
        "weathercarpet.MixinCloudChecking"),
    common_remoteio_MixinLocalizationUpdater(Side.COMMON, require(TargetedMod.REMOTEIO),
        "remoteio.MixinLocalizationUpdater"),
    common_birdsnest_MixinBirdNests(Side.COMMON, require(TargetedMod.BIRDSNEST), "birdsnest.MixinBirdNests"),
    common_birdsnest_MixinOnJoinWorldHandlerBird(Side.COMMON, require(TargetedMod.BIRDSNEST),
        "birdsnest.MixinOnJoinWorldHandlerBird"),
    common_thaumcraft_MixinBlockAiry(Side.COMMON, require(TargetedMod.THAUMCRAFT4), "thaumcraft.MixinBlockAiry"),
    common_thaumcraft_MixinMappingThread(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinMappingThread"),
    common_thaumcraft_MixinEventHandlerEntity(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinEventHandlerEntity"),
    common_codechickencore_MixinClassDiscoverer(Side.COMMON, require(TargetedMod.CODECHICKENCORE),
        "codechickencore.MixinClassDiscoverer"),
    common_traincraft_MixinTierRecipeManager(Side.COMMON, require(TargetedMod.TRAINCRAFT),
        "traincraft.MixinTierRecipeManager"),
    common_lootpluplus_MixinLootPPHelper(Side.COMMON, require(TargetedMod.LOOTPLUSPLUS),
        "lootpluplus.MixinLootPPHelper"),
    common_matmos_MixinForgeBase(Side.COMMON, require(TargetedMod.MATMOS), "matmos.MixinForgeBase"),
    common_matmos_MixinBlockCountModule(Side.COMMON, require(TargetedMod.MATMOS), "matmos.MixinBlockCountModule"),

    common_matmos_MixinScanVolumetric(Side.COMMON, require(TargetedMod.MATMOS), "matmos.MixinScanVolumetric"),

    common_matmos_MixinScanRaycast(Side.COMMON, require(TargetedMod.MATMOS), "matmos.MixinScanRaycast"),
    common_matmos_MixinScannerModule(Side.COMMON, require(TargetedMod.MATMOS), "matmos.MixinScannerModule"),
    common_matmos_MixinSheetDataPackage(Side.COMMON, require(TargetedMod.MATMOS), "matmos.MixinSheetDataPackage"),
    common_thaumcraftminusthaumcraft_MixinUnthaumic(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraftminusthaumcraft.MixinUnthaumic"),
    common_automagy_MixinAutomagyEventHandler(Side.COMMON, require(TargetedMod.AUTOMAGY),
        "automagy.MixinAutomagyEventHandler"),
    common_thaumcraft_MixinPatchBiomeGenMagicalForest(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinPatchBiomeGenMagicalForest"),
    common_thaumcraft_MixinPatchBlockMagicalLeavesPerformances(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinPatchBlockMagicalLeavesPerformances"),

    common_ragdollcorpse_MixinEventHandler_Ragdoll(Side.COMMON, require(TargetedMod.RAGDOLLCORPSE),
        "ragdollcorpse.MixinEventHandler_Ragdoll"),
    common_thaumcraft_MixinScanManager(Side.COMMON, require(TargetedMod.THAUMCRAFT4), "thaumcraft.MixinScanManager"),
    common_thaumcraft_MixinThaumcraftCraftingManager(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinThaumcraftCraftingManager"),
    common_thaumcraft_MixinThaumcraftApi(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinThaumcraftApi"),
    common_gadomancy_MixinInfusionVisualDisguiseArmor(Side.COMMON, require(TargetedMod.GADOMANCY),
        "gadomancy.MixinInfusionVisualDisguiseArmor"),
    common_extrautilities_MixinThaumcraftHelperEU(Side.COMMON, require(TargetedMod.EXTRAUTILS),
        "extrautilities.MixinThaumcraftHelperEU"),
    client_extrautilities_MixinBlockBreakingRegistry(Side.CLIENT, require(TargetedMod.EXTRAUTILS),
        "extrautilities.MixinBlockBreakingRegistry"),
    common_eternalfrost_MixinEFConfiguration(Side.COMMON, require(TargetedMod.ETERNALFROST),
        "eternalfrost.MixinEFConfiguration"),
    common_eternalfrost_mobspawningfix_MixinBlockMobSpawner2(Side.COMMON, require(TargetedMod.ETERNALFROST),
        "eternalfrost.mobspawningfix.MixinBlockMobSpawner2"),
    common_eternalfrost_mobspawningfix_MixinBlockMobSpawner3(Side.COMMON, require(TargetedMod.ETERNALFROST),
        "eternalfrost.mobspawningfix.MixinBlockMobSpawner3"),
    common_eternalfrost_mobspawningfix_MixinVanillaMobSpawnerBaseLogic(Side.COMMON, require(TargetedMod.ETERNALFROST),
        "eternalfrost.mobspawningfix.MixinVanillaMobSpawnerBaseLogic"),
    common_eternalfrost_classcastexceptionfix_MixinTileEntitySnowbarkChestRenderer(Side.COMMON,
        require(TargetedMod.ETERNALFROST), "eternalfrost.classcastexceptionfix.MixinTileEntitySnowbarkChestRenderer"),
    common_blocklings_MixinItemBlockling(Side.COMMON, require(TargetedMod.BLOCKLINGS), "blocklings.MixinItemBlockling"),
    common_colorediron_MixinColoredIron(Side.COMMON, require(TargetedMod.COLOREDIRON), "colorediron.MixinColoredIron"),
    common_nei_MixinWorldOverlayRenderer(Side.COMMON, require(TargetedMod.NEI), "nei.MixinWorldOverlayRenderer"),
    common_buildcraft_addon_oiltweaks_MixinBuildCraftConfig(Side.COMMON, require(TargetedMod.BUILDCRAFTOILTWEAKS),
        "buildcraft.addon.oiltweaks.MixinBuildCraftConfig"),
    common_mankini_MixinBatMankiniJump(Side.COMMON, require(TargetedMod.MANKINI), "mankini.MixinBatMankiniJump"),

    common_experienceore_MixinWorldGenHandlerExperienceOre(Side.COMMON, require(TargetedMod.EXPERIENCEORE),
        "experienceore.MixinWorldGenHandlerExperienceOre"),
    common_buildcraft_MixinSpringPopulate(Side.COMMON, require(TargetedMod.BUILDCRAFT),
        "buildcraft.MixinSpringPopulate"),

    common_diseasecraft_MixinMedUtils(Side.COMMON, require(TargetedMod.DISEASECRAFT), "diseasecraft.MixinMedUtils"),
    common_potionshards_MixinEventHandlerPotionShards(Side.COMMON, require(TargetedMod.POTIONSHARDS),
        "potionshards.MixinEventHandlerPotionShards"),
    common_goblins_MixinMobSpawnerGoblinLogic(Side.COMMON, require(TargetedMod.GOBLINS),
        "goblins.MixinMobSpawnerGoblinLogic"),
    client_goblins_MixinGoblinClientProxy(Side.CLIENT, require(TargetedMod.GOBLINS), "goblins.MixinGoblinClientProxy"),
    common_xtracraft_MixinXCEntityGod(Side.COMMON, require(TargetedMod.XTRACRAFT), "xtracraft.MixinXCEntityGod"),
    common_goblins_MixinGOBLINWorldGenGVillage1(Side.COMMON, require(TargetedMod.GOBLINS),
        "goblins.MixinGOBLINWorldGenGVillage1"),
    common_goblins_MixinGOBLINWorldGenFireplace(Side.COMMON, require(TargetedMod.GOBLINS),
        "goblins.MixinGOBLINWorldGenFireplace"),
    common_goblins_MixinGOBLINWorldGenHuts(Side.COMMON, require(TargetedMod.GOBLINS),
        "goblins.MixinGOBLINWorldGenHuts"),
    common_fossilsandarcheologyrevivals_MixinAcademyGenerator(Side.COMMON,
        require(TargetedMod.FOSSILANDARCHEOLOGYREVIVAL), "fossilsandarcheologyrevivals.MixinAcademyGenerator"),
    common_fossilsandarcheologyrevivals_MixinTarGenerator(Side.COMMON, require(TargetedMod.FOSSILANDARCHEOLOGYREVIVAL),
        "fossilsandarcheologyrevivals.MixinTarGenerator"),
    common_fossilsandarcheologyrevivals_MixinShipWreckGenerator(Side.COMMON,
        require(TargetedMod.FOSSILANDARCHEOLOGYREVIVAL), "fossilsandarcheologyrevivals.MixinShipWreckGenerator"),
    common_fossilsandarcheologyrevivals_MixinWorldGenMiscStructures(Side.COMMON,
        require(TargetedMod.FOSSILANDARCHEOLOGYREVIVAL), "fossilsandarcheologyrevivals.MixinWorldGenMiscStructures"),

    common_atum_MixinWorldGenPyramid(Side.COMMON, require(TargetedMod.ATUM2), "atum.MixinWorldGenPyramid"),
    common_atum_MixinWorldGenOasis(Side.COMMON, require(TargetedMod.ATUM2), "atum.MixinWorldGenOasis"),
    common_atum_MixinWorldGenRuins(Side.COMMON, require(TargetedMod.ATUM2), "atum.MixinWorldGenRuins"),
    common_atum_MixinAtumWeightedLootSet(Side.COMMON, require(TargetedMod.ATUM2), "atum.MixinAtumWeightedLootSet"),
    common_mythandmonsters_MixinMAMWorldGenerator(Side.COMMON,
        require(TargetedMod.MYTHANDMONSTERS).and(require(TargetedMod.RECURRENTCOMPLEX)),
        "mythandmonsters.MixinMAMWorldGenerator"),
    common_mythandmonsters_MixinMAMClientProxy(Side.COMMON, require(TargetedMod.MYTHANDMONSTERS),
        "mythandmonsters.MixinMAMClientProxy"),
    common_hamsterific_MixinEntityHamster(Side.COMMON, require(TargetedMod.HAMSTERIFIC),
        "hamsterific.MixinEntityHamster"),
    common_ganysnether_MixinNetherWorldGenGanys(Side.COMMON, require(TargetedMod.HAMSTERIFIC),
        "ganysnether.MixinNetherWorldGenGanys"),
    common_thaumicrevelation_MixinKeyHandlerTHAUMREV(Side.COMMON, require(TargetedMod.THAUMICREVELEATION),
        "thaumicrevelation.MixinKeyHandlerTHAUMREV"),
    common_industrialupgrade_MixinRegisterOreDict(Side.COMMON, require(TargetedMod.INDUSTRIALUPGRADE),
        "industrialupgrade.MixinRegisterOreDict"),
    common_gemsnjewels_MixinModBlocksGemsNJewels(Side.COMMON, require(TargetedMod.GEMSNJEWELS),
        "gemsnjewels.MixinModBlocksGemsNJewels"),
    common_farlanders_MixinVillageRoad(Side.COMMON, require(TargetedMod.FARLANDERS), "farlanders.MixinVillageRoad"),
    common_farlanders_MixinEntityEnderGolem(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityEnderGolem"),
    common_farlanders_MixinEntityEnderminion(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityEnderminion"),
    common_farlanders_MixinEntityFarlander(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityFarlander"),
    common_farlanders_MixinEntityLootr(Side.COMMON, require(TargetedMod.FARLANDERS), "farlanders.MixinEntityLootr"),
    common_farlanders_MixinEntityMysticEnderminion(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityMysticEnderminion"),
    common_farlanders_MixinEntityWanderer(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityWanderer"),
    common_farlanders_MixinEntityTitan(Side.COMMON, require(TargetedMod.FARLANDERS), "farlanders.MixinEntityTitan"),
    common_farlanders_MixinEntityRebel(Side.COMMON, require(TargetedMod.FARLANDERS), "farlanders.MixinEntityRebel"),
    common_farlanders_MixinEntityMystic(Side.COMMON, require(TargetedMod.FARLANDERS), "farlanders.MixinEntityMystic"),
    common_farlanders_MixinEntityEnderGuardian(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityEnderGuardian"),
    common_farlanders_MixinEntityElder(Side.COMMON, require(TargetedMod.FARLANDERS), "farlanders.MixinEntityElder"),
    common_farlanders_MixinEntityFanEnderman(Side.COMMON, require(TargetedMod.FARLANDERS),
        "farlanders.MixinEntityFanEnderman"),
    common_thaumcraft_MixinFixCascadingWorldGenFromThaumcraftWorldGenerator(Side.COMMON,
        require(TargetedMod.THAUMCRAFT4), "thaumcraft.MixinFixCascadingWorldGenFromThaumcraftWorldGenerator"),
    common_thaumcraft_MixinWorldGenGreatwoodTrees(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinWorldGenGreatwoodTrees"),
    common_thaumcraft_MixinWorldGenSilverwoodTrees(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinWorldGenSilverwoodTrees"),
    common_thaumcraft_MixinWorldGenEldritchRing(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinWorldGenEldritchRing"),

    common_thaumcraft_MixinThaumcraftUtils(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinThaumcraftUtils"),
    common_thaumcraft_MixinTileNode(Side.COMMON, require(TargetedMod.THAUMCRAFT4), "thaumcraft.MixinTileNode"),

    common_thaumcraft_MixinWorldGenCustomFlowersSide(Side.COMMON, require(TargetedMod.THAUMCRAFT4),
        "thaumcraft.MixinWorldGenCustomFlowers"),

    common_masterchef_MixinWorldGenNori(Side.COMMON, require(TargetedMod.MASTERCHEF), "masterchef.MixinWorldGenNori"),
    common_gardenstuff_MixinWorldGenCandelilla(Side.COMMON, require(TargetedMod.GARDENSTUFF),
        "gardenstuff.MixinWorldGenCandelilla"),
    common_pamsharvestcraft_MixinFixWorldGenPamFruitTree(Side.COMMON, require(TargetedMod.PAMSHARVESTCRAFT),
        "pamsharvestcraft.MixinFixWorldGenPamFruitTree"),
    common_steamcraft2_MixinFixCascadingFromWorldGenBrassTree(Side.COMMON, require(TargetedMod.STEAMCRAFT2),
        "steamcraft2.MixinFixCascadingFromWorldGenBrassTree"),
    common_cofhcore_MixinCOFHCORE(Side.COMMON, require(TargetedMod.COFHCORE), "cofhcore.MixinCOFHCORE"),
    common_cofhcore_MixinUpdateCheckThreadCOFH(Side.COMMON, require(TargetedMod.COFHCORE),
        "cofhcore.MixinUpdateCheckThreadCOFH"),
    common_cofhcore_fixoredictcrash_MixinOreDictionaryArbiter(Side.COMMON, require(TargetedMod.COFHCORE),
        "cofhcore.fixoredictcrash.MixinOreDictionaryArbiter"),
    common_cofhcore_MixinBlockTickingWater(Side.COMMON, require(TargetedMod.COFHCORE),
        "cofhcore.MixinBlockTickingWater"),
    common_slimecarnage_MixinFixCascadingFromWorldGenSlimeCarnage(Side.COMMON, require(TargetedMod.SLIMECARNAGE),
        "slimecarnage.MixinFixCascadingFromWorldGenSlimeCarnage"),

    common_slimecarnage_MixinWorldGenSewers(Side.COMMON, require(TargetedMod.SLIMECARNAGE),
        "slimecarnage.MixinWorldGenSewers"),

    common_slimecarnage_MixinWorldGenMadLab(Side.COMMON, require(TargetedMod.SLIMECARNAGE),
        "slimecarnage.MixinWorldGenMadLab"),
    common_spiriteores_MixinSpiritOres(Side.COMMON, require(TargetedMod.SPIRITEORES), "spiriteores.MixinSpiritOres"),
    common_spiriteores_MixinSpiritOresGenerator(Side.COMMON, require(TargetedMod.SPIRITEORES),
        "spiriteores.MixinSpiritOresGenerator"),
    common_familliarsAPI_MixinFamiliar(Side.COMMON, require(TargetedMod.FAMILIARSAPI), "familliarsAPI.MixinFamiliar"),
    common_pamsharvestcraft_MixinFixPamsTreesCascadingWorldgenLag(Side.COMMON, require(TargetedMod.PAMSHARVESTCRAFT),
        "pamsharvestcraft.MixinFixPamsTreesCascadingWorldgenLag"),
    common_hardcorewither_MixinEventHandler(Side.COMMON, require(TargetedMod.HARDCOREWITHER),
        "hardcorewither.MixinEventHandler"),
    common_shincolle_MixinEVENT_BUS_EventHandler(Side.COMMON, require(TargetedMod.SHINCOLLE),
        "shincolle.MixinEVENT_BUS_EventHandler"),
    common_betterburning_MixinBetterBurning(Side.COMMON, require(TargetedMod.BETTERBURNING),
        "betterburning.MixinBetterBurning"),
    common_MixinFixCascadingFromShipwreckGen(Side.COMMON, require(TargetedMod.SHIPEWRECK),
        "shipwreck.MixinFixCascadingFromShipwreckGen"),
    common_shincolle_MixinFixCascadingFromWorldGenPolyGravel(Side.COMMON, require(TargetedMod.SHINCOLLE),
        "shincolle.MixinFixCascadingFromWorldGenPolyGravel"),
    common_shincolle_MixinFixCascadingFromShinColleWorldGen(Side.COMMON, require(TargetedMod.SHINCOLLE),
        "shincolle.MixinFixCascadingFromShinColleWorldGen"),
    common_obsgreenery_MixinWorldGenTreeBase(Side.COMMON, require(TargetedMod.OBSGREENERY),
        "obsgreenery.MixinWorldGenTreeBase"),
    common_obsgreenery_MixinWorldGenTreeBlackWattle(Side.COMMON, require(TargetedMod.OBSGREENERY),
        "obsgreenery.MixinWorldGenTreeBlackWattle"),

    common_minefactoryreloaded_MixinWorldGenMassiveTree(Side.COMMON, require(TargetedMod.MINEFACTORYRELOADED),
        "minefactoryreloaded.MixinWorldGenMassiveTree"),
    common_minefactoryreloaded_MixinFixCascadingforMineFactoryReloadedWorldGen(Side.COMMON,
        require(TargetedMod.MINEFACTORYRELOADED),
        "minefactoryreloaded.MixinFixCascadingforMineFactoryReloadedWorldGen"),
    common_minefactoryreloaded_MixinFixWorldGenLakesMetaCascadingWorldgenLag(Side.COMMON,
        require(TargetedMod.MINEFACTORYRELOADED), "minefactoryreloaded.MixinFixWorldGenLakesMetaCascadingWorldgenLag"),
    common_minefactoryreloaded_MixinFixRubberTreesCascadingWorldgenLag(Side.COMMON,
        require(TargetedMod.MINEFACTORYRELOADED), "minefactoryreloaded.MixinFixRubberTreesCascadingWorldgenLag"),
    common_minefactoryreloaded_MixinFixNoSuchMethodException(Side.COMMON, require(TargetedMod.MINEFACTORYRELOADED),
        "minefactoryreloaded.MixinFixNoSuchMethodException"),
    common_entityculling_MixinCullTask(Side.COMMON, require(TargetedMod.ENTITYCULLING), "entityculling.MixinCullTask"),

    common_core_MixinGodZillaFix(Side.COMMON, always(), "core.MixinGodZillaFix"),
    common_witchery_MixinGenericEventsWitchery(Side.COMMON, always(), "witchery.MixinGenericEventsWitchery"),
    common_witchery_MixinWorldProviderTorment(Side.COMMON, always(), "witchery.MixinWorldProviderTorment"),
    common_opis_MixinopisProfilerEvent(Side.COMMON, require(TargetedMod.OPIS), "opis.MixinopisProfilerEvent"),
    common_core_MixinStatList(Side.COMMON, always(), "core.MixinStatList"),

    common_malcore_MixinVersionInfo(Side.COMMON, require(TargetedMod.MALCORE), "malcore.MixinVersionInfo"),

    common_kitchencraft_MixinKitchenCraftMachines(Side.COMMON, require(TargetedMod.KITCHENCRAFT),
        "kitchencraft.MixinKitchenCraftMachines"),
    common_grim3212_MixinGrimModule(Side.COMMON, require(TargetedMod.GRIM3212), "grim3212.MixinGrimModule"),

    common_chromaticraft_MixinDungeonGenerator(Side.COMMON, require(TargetedMod.CHROMATICRAFT),
        "chromaticraft.MixinDungeonGenerator"),

    // CLIENT MIXINS

    client_core_MixinGuiNewChat(Side.CLIENT, always(), "core.MixinGuiNewChat"),
    client_instrumentus_MixinPlayerSpecials(Side.CLIENT, require(TargetedMod.INSTRUMENTUS),
        "instrumentus.MixinPlayerSpecials"),

    client_core_MixinGui(Side.CLIENT, always(), "core.MixinGui"),
    client_core_MixinRenderItem(Side.CLIENT, avoid(TargetedMod.FASTCRAFT), "core.MixinRenderItem"),
    client_core_MixinItemRenderer(Side.CLIENT, always(), "core.MixinItemRenderer"),
    client_core_MixinRenderGlobal(Side.CLIENT, avoid(TargetedMod.FASTCRAFT).and(avoid(TargetedMod.OPTIFINE)),
        "core.MixinRenderGlobal"),
    client_core_MixinRenderManager(Side.CLIENT, avoid(TargetedMod.SKINPORT).and(avoid(TargetedMod.ANGELICA)),
        "core.MixinRenderManager"),
    client_essenceofthegod_MixinBarTickHandler(Side.CLIENT, always(), "essenceofthegod.MixinBarTickHandler"),
    client_essenceofthegod_MixinPlayerStats(Side.CLIENT, always(), "essenceofthegod.MixinPlayerStats"),
    client_manametalmod_MixinEventGUI(Side.CLIENT, require(TargetedMod.MANAMETAL), "manametalmod.MixinEventGUI"),

    client_davincivessels_MixinShipKeyHandler(Side.CLIENT, require(TargetedMod.DAVINCIVESSELS),
        "davincivessels.MixinShipKeyHandler"),
    client_practicallogistics_MixinEventRegistry(Side.CLIENT, require(TargetedMod.PRACTICALLOGISTICS),
        "practicallogistics.MixinEventRegistry"),
    client_salutation_MixinSalutationClientHandler(Side.CLIENT, require(TargetedMod.SALUTATION),
        "salutation.MixinSalutationClientHandler"),

    common_core_MixinEntityPlayer(Side.COMMON, always(), "core.MixinEntityPlayer"),

    common_core_MixinPathFinder(Side.COMMON, m -> OptimizationsandTweaksConfig.enablePathFindingOptimizations,
        "core.MixinPathFinder"),
    common_core_MixinPathEntity(Side.COMMON, m -> OptimizationsandTweaksConfig.enablePathFindingOptimizations,
        "core.MixinPathEntity"),
    common_core_MixinPathNavigate(Side.COMMON, m -> OptimizationsandTweaksConfig.enablePathFindingOptimizations,
        "core.MixinPathNavigate"),
    // Devtools-only AI trace (see AiEventTrace) — applied only with -Doat.aitrace=true, never in prod.
    common_ai_MixinEntityAIPanic(Side.COMMON, m -> Boolean.getBoolean("oat.aitrace"), "ai.MixinEntityAIPanic"),
    common_angelica_MixinClientProxy(Side.COMMON, require(TargetedMod.ANGELICA), "angelica.MixinClientProxy"),
    client_core_MixinEntitySpellParticleFX(Side.CLIENT, always(), "core.MixinEntitySpellParticleFX"),
    client_core_MixinCodecIBXM(Side.CLIENT, always(), "core.MixinCodecIBXM"),

    client_core_MixinTesselator(Side.CLIENT, avoid(TargetedMod.OPTIFINE), "core.MixinTesselator"),

    common_core_MixinNetHandlerPlayClient(Side.COMMON, always(), "core.MixinNetHandlerPlayClient"),
    client_core_MixinEntityRenderer(Side.CLIENT, avoid(TargetedMod.OPTIFINE).and(avoid(TargetedMod.FASTCRAFT))
        .and(avoid(TargetedMod.ALFHEIM)), "core.MixinEntityRenderer"),
    client_core_MixinModelRenderer(Side.CLIENT, avoid(TargetedMod.OPTIFINE).and(avoid(TargetedMod.ANGELICA)),
        "core.MixinModelRenderer"),
    client_core_MixinStitcher_Slot(Side.CLIENT, always(), "core.MixinStitcher_Slot"),

    client_core_MixinStitcher(Side.CLIENT, avoid(TargetedMod.FALSETWEAKS), "core.MixinStitcher"),
    client_core_MixinTextureUtil(Side.CLIENT, always(), "core.MixinTextureUtil"),
    client_manametal_MixinEventFog(Side.CLIENT, always(), "manametal.MixinEventFog"),

    // MOD-FILTERED MIXINS

    // The modFilter argument is a predicate, so you can also use the .and(),
    // .or(), and .negate() methods to mix and match multiple predicates.
    ;

    @Getter
    public final Side side;
    /**
     * Mod-presence filter only (require/avoid TargetedMod combinations, or {@link #always()}).
     * Per-mixin enable/disable is no longer stored here: it is resolved generically by
     * {@link MixinConfigResolver} from the entry name (see {@link #getFilter()}).
     */
    public final Predicate<List<ITargetedMod>> filter;
    @Getter
    public final String mixin;

    /**
     * Combines the declared mod-presence filter with the generic, name-driven enable/disable
     * resolution (category toggle + disabledMixins/forceEnabledMixins + built-in default).
     */
    @Override
    public Predicate<List<ITargetedMod>> getFilter() {
        return filter.and(mods -> MixinConfigResolver.INSTANCE.isEnabled(this));
    }

    static Predicate<List<ITargetedMod>> require(TargetedMod in) {
        return modList -> modList.contains(in);
    }

    static Predicate<List<ITargetedMod>> avoid(TargetedMod in) {
        return modList -> !modList.contains(in);
    }

    static Predicate<List<ITargetedMod>> always() {
        return modList -> true;
    }
}
