[package]
name = "optimizationsandtweaks_blocksupdates"
version = "0.1.0"
edition = "2021"

[lib]
name = "optimizationsandtweaks_blocksupdates"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
lazy_static = "1.5.0"
leaktracer = "0.1"
rayon = "1.10"
crossbeam = "0.8"
lru = "0.12"
optimizationsandtweaks_shared = { path = "../optimizationsandtweaks_shared" }