package fr.iamacat.optimizationsandtweaks.mixins.common.manametalmod;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.chunk.Chunk;

import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;

/**
 * Fixes cascading worldgen caused by ManaMetalMod's dungeon/village area clearing.
 * <p>
 * Unlike this mod's other {@code MixinFixCascading*} fixes, {@code project.studio.manametalmod.core
 * .AreaClear#clearArea(Random, World, int, int, int, int)} is a <b>deliberately cross-chunk</b>
 * operation: it flattens/clears a square of {@code (clearsize + 16) x (clearsize + 16)} blocks
 * (an 8-block wall margin is added on every side of the caller-supplied {@code clearsize}) around a
 * dungeon/village origin. Callers pass {@code clearsize} of 32 ({@code WorldGenDungeonDoor}) or
 * {@code big + 8} ({@code WorldGenDungeon#spawnSchematicVillage}/{@code spawnDungeonSHBadGuy}), so the
 * cleared square is routinely 48+ blocks wide/long — i.e. up to 3x3 chunks — which is content the mod
 * intentionally wants cleared, not an accident to truncate. This is Archetype B: a chunk-local
 * {@code Chunk.func_150807_a} redirect alone would be wrong here, because it would silently force
 * {@code World.getChunkFromChunkCoords} to generate whatever neighbour chunk each column happens to
 * land in (that call always returns a chunk, generating one if absent) — the exact cascade we're
 * trying to remove, just moved one call deeper.
 * <p>
 * Per (x, z) column in the cleared square, {@code clearArea} calls four vanilla {@code World} members
 * that can each reach an out-of-bounds neighbour chunk:
 * <ul>
 * <li>{@code func_72825_h} ({@code getTopSolidOrLiquidBlock}) — read, used twice per column (once to
 * bound the vertical clear loop, once to find the surface for the biome-top-block placement below);
 * <li>{@code func_147468_f} ({@code setBlockToAir}) — write, used to actually clear blocks;
 * <li>{@code func_72807_a} ({@code getBiomeGenForCoords}) — read, used to pick the surface block; and
 * <li>{@code func_147449_b} ({@code setBlock(x,y,z,block)}, 3-arg) — write, places the biome's top
 * block at the new surface. Like {@code MixinFixCascadingFromManaMetalEventCave}/{@code WorldGenRock},
 * this 3-arg overload forwards to {@code setBlock(...,3)}, whose flag&amp;1 fires
 * {@code notifyBlockChange} — a neighbour-notify cascade in its own right, independent of the
 * multi-chunk span.
 * </ul>
 * Every one of these is redirected to first check {@code World.getChunkProvider().chunkExists} for the
 * column's own chunk coordinates:
 * <ul>
 * <li>if that chunk is <b>not</b> loaded/generated yet, the call is skipped outright — the read
 * returns a safe sentinel (0 height / a fallback biome) and the write is dropped — so nothing forces
 * that neighbour chunk to generate mid-populate. The corresponding slice of the clear area is simply
 * left untouched (same tradeoff as {@code MixinWorldGenBalance}: a partial structure edge beats a
 * generation cascade);
 * <li>if it <b>is</b> loaded, the read passes through to the real vanilla call (correctness for the
 * legitimate, already-generated part of the span is unchanged), and the write goes straight into that
 * chunk's block storage via {@code Chunk.func_150807_a} instead of {@code World.setBlock}/
 * {@code setBlockToAir}, so it never fires the neighbour notify that would otherwise cascade into a
 * chunk 1 further out — exactly like this mod's other {@code MixinFixCascading*} fixes.
 * </ul>
 * Net effect: within the region that is already loaded (the common case — the origin chunk and its
 * immediate neighbours are generated by the time a dungeon/village populates), {@code clearArea}
 * behaves byte-for-byte as before. Only the columns that would otherwise reach into a not-yet-generated
 * chunk are skipped, which trades a possibly-truncated clear/decoration edge for never forcing
 * out-of-order chunk generation.
 *
 * @author iamacatfr
 */
@Mixin(targets = "project.studio.manametalmod.core.AreaClear", remap = false)
public class MixinFixCascadingFromManaMetalAreaClear {

    @Redirect(
        method = "clearArea",
        at = @At(value = "INVOKE", target = "Lnet/minecraft/world/World;func_72825_h(II)I"),
        remap = false)
    private int optimizationsAndTweaks$getTopSolidOrLiquidBlockGuarded(World world, int x, int z) {
        if (!world.getChunkProvider()
            .chunkExists(x >> 4, z >> 4)) {
            // Target column is outside the loaded/generated area: don't force that neighbour chunk to
            // generate just to read its height. 0 is a safe "no known surface" sentinel — every caller
            // of this value only uses it to bound/aim a write, and those writes are independently
            // guarded below, so an unreachable/incorrect height here never reaches the world.
            return 0;
        }
        return world.getTopSolidOrLiquidBlock(x, z);
    }

    @Redirect(
        method = "clearArea",
        at = @At(value = "INVOKE", target = "Lnet/minecraft/world/World;func_72807_a(II)Lnet/minecraft/world/biome/BiomeGenBase;"),
        remap = false)
    private BiomeGenBase optimizationsAndTweaks$getBiomeGenForCoordsGuarded(World world, int x, int z) {
        if (!world.getChunkProvider()
            .chunkExists(x >> 4, z >> 4)) {
            // Same reasoning as above: skip the read rather than force-generate the neighbour chunk.
            // The fallback biome is never actually placed since the follow-up setBlock call for this
            // same column is independently guarded and will drop the write.
            return BiomeGenBase.getBiome(0);
        }
        return world.getBiomeGenForCoords(x, z);
    }

    @Redirect(
        method = "clearArea",
        at = @At(value = "INVOKE", target = "Lnet/minecraft/world/World;func_147468_f(III)Z"),
        remap = false)
    private boolean optimizationsAndTweaks$setBlockToAirGuarded(World world, int x, int y, int z) {
        return optimizationsAndTweaks$chunkLocalSetIfLoaded(world, x, y, z, Blocks.air, 0);
    }

    @Redirect(
        method = "clearArea",
        at = @At(value = "INVOKE", target = "Lnet/minecraft/world/World;func_147449_b(IIILnet/minecraft/block/Block;)Z"),
        remap = false)
    private boolean optimizationsAndTweaks$setBlockGuarded(World world, int x, int y, int z, Block block) {
        return optimizationsAndTweaks$chunkLocalSetIfLoaded(world, x, y, z, block, 0);
    }

    /**
     * Write a block straight into its column's chunk storage, but only if that chunk is already
     * loaded/generated. If it isn't, the write is dropped instead of falling through to
     * {@code World.getChunkFromChunkCoords} (which would force-generate the missing chunk — the very
     * cascade this mixin removes). When the chunk is loaded, the direct {@code Chunk.func_150807_a}
     * write bypasses the neighbour notify/light propagation that {@code World.setBlock}/
     * {@code setBlockToAir} would trigger at a chunk edge, exactly like this mod's other
     * {@code MixinFixCascading*} fixes.
     */
    @Unique
    private static boolean optimizationsAndTweaks$chunkLocalSetIfLoaded(World world, int x, int y, int z,
        Block block, int meta) {
        if (y < 0 || y >= 256) {
            return false;
        }
        int chunkX = x >> 4;
        int chunkZ = z >> 4;
        if (!world.getChunkProvider()
            .chunkExists(chunkX, chunkZ)) {
            return false;
        }
        Chunk chunk = world.getChunkFromChunkCoords(chunkX, chunkZ);
        return chunk.func_150807_a(x & 15, y, z & 15, block, meta);
    }
}
